import { Expression } from './Expression';
import { LambdaExpression } from './LambdaExpression';
import { ParameterExpression } from './ParameterExpression';
import { BinaryOperator, BinaryExpression } from './BinaryExpression';
import { PropertyAccessExpression } from './PropertyAccessExpression';
import { ConstantExpression } from './ConstantExpression';
import { PropertyAssignmentExpression } from './PropertyAssignmentExpression';
import { ObjectLiteralExpression } from './ObjectLiteralExpression';
import { CallExpression } from './CallExpression';
export declare function lambda(parameters: ParameterExpression[], body: Expression): LambdaExpression;
export declare function parameter(name: string): ParameterExpression;
export declare function binary(left: Expression, operator: BinaryOperator, right: Expression): BinaryExpression;
export declare function strictEquals(left: Expression, right: Expression): BinaryExpression;
export declare function equals(left: Expression, right: Expression): BinaryExpression;
export declare function and(left: Expression, right: Expression): BinaryExpression;
export declare function or(left: Expression, right: Expression): BinaryExpression;
export declare function propertyAccess(expression: Expression, name: string): PropertyAccessExpression;
export declare function constant(value: any): ConstantExpression;
export declare function objectLiteral(properties: PropertyAssignmentExpression[]): ObjectLiteralExpression;
export declare function propertyAssignment(name: string, expression: Expression): PropertyAssignmentExpression;
export declare function call(calleeExpression: Expression, ...args: Expression[]): CallExpression;
